#YAML
# start_date: 2000-01-19
use_forecast_weight_estimates: False
use_forecast_div_mult_estimates: False
use_instrument_weight_estimates: False
use_instrument_div_mult_estimates: False
use_forecast_scale_estimates: False
#
#
#
#
#
#
#
# Raw data
#
#
# Trading rules
#
volatility_calculation:
  func: "sysquant.estimators.vol.mixed_vol_calc"
  days: 35
  min_periods: 10
  vol_abs_min: 0.0000000001
  slow_vol_years: 20
  proportion_of_slow_vol: 0.35
  backfill: True
#
use_attenuation:
   - 'breakout10'
   - 'breakout20'
   - 'breakout40'
   - 'breakout80'
   - 'breakout160'
   - 'breakout320'
   - 'relmomentum10'
   - 'relmomentum20'
   - 'relmomentum40'
   - 'relmomentum80'
   - 'mrinasset1000'
   - 'assettrend2'
   - 'assettrend4'
   - 'assettrend8'
   - 'assettrend16'
   - 'assettrend32'
   - 'assettrend64'
   - 'normmom2'
   - 'normmom4'
   - 'normmom8'
   - 'normmom16'
   - 'normmom32'
   - 'normmom64'
   - 'momentum4'
   - 'momentum8'
   - 'momentum16'
   - 'momentum32'
   - 'momentum64'
#
trading_rules:
  breakout10:
     function: systems.provided.rules.breakout.breakout
     data:
         - "rawdata.get_daily_prices"
     other_args:
       lookback: 10
  breakout20:
     function: systems.provided.rules.breakout.breakout
     data:
         - "rawdata.get_daily_prices"
     other_args:
       lookback: 20
  breakout40:
     function: systems.provided.rules.breakout.breakout
     data:
         - "rawdata.get_daily_prices"
     other_args:
       lookback: 40
  breakout80:
     function: systems.provided.rules.breakout.breakout
     data:
         - "rawdata.get_daily_prices"
     other_args:
       lookback: 80
  breakout160:
     function: systems.provided.rules.breakout.breakout
     data:
         - "rawdata.get_daily_prices"
     other_args:
       lookback: 160
  breakout320:
     function: systems.provided.rules.breakout.breakout
     data:
         - "rawdata.get_daily_prices"
     other_args:
       lookback: 320
  relmomentum10:
     function: systems.provided.rules.rel_mom.relative_momentum
     data:
         - "rawdata.get_cumulative_daily_vol_normalised_returns"
         - "rawdata.normalised_price_for_asset_class"
     other_args:
       horizon: 10
  relmomentum20:
     function: systems.provided.rules.rel_mom.relative_momentum
     data:
         - "rawdata.get_cumulative_daily_vol_normalised_returns"
         - "rawdata.normalised_price_for_asset_class"
     other_args:
       horizon: 20
  relmomentum40:
     function: systems.provided.rules.rel_mom.relative_momentum
     data:
         - "rawdata.get_cumulative_daily_vol_normalised_returns"
         - "rawdata.normalised_price_for_asset_class"
     other_args:
       horizon: 40
  relmomentum80:
     function: systems.provided.rules.rel_mom.relative_momentum
     data:
         - "rawdata.get_cumulative_daily_vol_normalised_returns"
         - "rawdata.normalised_price_for_asset_class"
     other_args:
       horizon: 80
  mrinasset1000:
     function: systems.provided.rules.cs_mr.cross_sectional_mean_reversion
     data:
         - "rawdata.get_cumulative_daily_vol_normalised_returns"
         - "rawdata.normalised_price_for_asset_class"
     other_args:
       horizon: 1000
  carry10:
     function: systems.provided.rules.carry.carry
     data:
         - "rawdata.raw_carry"
     other_args:
         smooth_days: 10
  carry30:
     function: systems.provided.rules.carry.carry
     data:
         - "rawdata.raw_carry"
     other_args:
         smooth_days: 30
  carry60:
     function: systems.provided.rules.carry.carry
     data:
         - "rawdata.raw_carry"
     other_args:
         smooth_days: 60
  carry125:
     function: systems.provided.rules.carry.carry
     data:
         - "rawdata.raw_carry"
     other_args:
         smooth_days: 125
  assettrend2:
     function: systems.provided.rules.ewmac.ewmac_calc_vol
     data:
         - "rawdata.normalised_price_for_asset_class"
     other_args:
         Lfast: 2
         Lslow: 8
  assettrend4:
     function: systems.provided.rules.ewmac.ewmac_calc_vol
     data:
         - "rawdata.normalised_price_for_asset_class"
     other_args:
         Lfast: 4
         Lslow: 16
  assettrend8:
     function: systems.provided.rules.ewmac.ewmac_calc_vol
     data:
         - "rawdata.normalised_price_for_asset_class"
     other_args:
         Lfast: 8
         Lslow: 32
  assettrend16:
     function: systems.provided.rules.ewmac.ewmac_calc_vol
     data:
         - "rawdata.normalised_price_for_asset_class"
     other_args:
         Lfast: 16
         Lslow: 64
  assettrend32:
     function: systems.provided.rules.ewmac.ewmac_calc_vol
     data:
         - "rawdata.normalised_price_for_asset_class"
     other_args:
         Lfast: 32
         Lslow: 128
  assettrend64:
     function: systems.provided.rules.ewmac.ewmac_calc_vol
     data:
         - "rawdata.normalised_price_for_asset_class"
     other_args:
         Lfast: 64
         Lslow: 256
  normmom2:
     function: systems.provided.rules.ewmac.ewmac_calc_vol
     data:
         - "rawdata.get_cumulative_daily_vol_normalised_returns"
     other_args:
         Lfast: 2
         Lslow: 8
  normmom4:
     function: systems.provided.rules.ewmac.ewmac_calc_vol
     data:
         - "rawdata.get_cumulative_daily_vol_normalised_returns"
     other_args:
         Lfast: 4
         Lslow: 16
  normmom8:
     function: systems.provided.rules.ewmac.ewmac_calc_vol
     data:
         - "rawdata.get_cumulative_daily_vol_normalised_returns"
     other_args:
         Lfast: 8
         Lslow: 32
  normmom16:
     function: systems.provided.rules.ewmac.ewmac_calc_vol
     data:
         - "rawdata.get_cumulative_daily_vol_normalised_returns"
     other_args:
         Lfast: 16
         Lslow: 64
  normmom32:
     function: systems.provided.rules.ewmac.ewmac_calc_vol
     data:
         - "rawdata.get_cumulative_daily_vol_normalised_returns"
     other_args:
         Lfast: 32
         Lslow: 128
  normmom64:
     function: systems.provided.rules.ewmac.ewmac_calc_vol
     data:
         - "rawdata.get_cumulative_daily_vol_normalised_returns"
     other_args:
         Lfast: 64
         Lslow: 256
  momentum4:
     function: systems.provided.rules.ewmac.ewmac
     data:
         - "rawdata.get_daily_prices"
         - "rawdata.daily_returns_volatility"
     other_args:
         Lfast: 4
         Lslow: 16
  momentum8:
     function: systems.provided.rules.ewmac.ewmac
     data:
         - "rawdata.get_daily_prices"
         - "rawdata.daily_returns_volatility"
     other_args:
         Lfast: 8
         Lslow: 32
  momentum16:
     function: systems.provided.rules.ewmac.ewmac
     data:
         - "rawdata.get_daily_prices"
         - "rawdata.daily_returns_volatility"
     other_args:
         Lfast: 16
         Lslow: 64
  momentum32:
     function: systems.provided.rules.ewmac.ewmac
     data:
         - "rawdata.get_daily_prices"
         - "rawdata.daily_returns_volatility"
     other_args:
         Lfast: 32
         Lslow: 128
  momentum64:
     function: systems.provided.rules.ewmac.ewmac
     data:
         - "rawdata.get_daily_prices"
         - "rawdata.daily_returns_volatility"
     other_args:
         Lfast: 64
         Lslow: 256
  relcarry:
     function: systems.provided.rules.carry.relative_carry
     data:
          - "rawdata.smoothed_carry"
          - "rawdata.median_carry_for_asset_class"
  skewabs365:
     function: systems.provided.rules.factors.factor_trading_rule
     data:
          - 'rawdata.get_demeanded_factor_value'
     other_args:
          smooth: 90
          _factor_name: 'neg_skew'
          _demean_method: 'historic_average_factor_value_all_assets'
          _lookback_days: 365
  skewabs180:
     function: systems.provided.rules.factors.factor_trading_rule
     data:
          - 'rawdata.get_demeanded_factor_value'
     other_args:
          smooth: 45
          _factor_name: 'neg_skew'
          _demean_method: 'historic_average_factor_value_all_assets'
          _lookback_days: 180
  skewrv365:
     function: systems.provided.rules.factors.factor_trading_rule
     data:
          - 'rawdata.get_demeanded_factor_value'
     other_args:
          smooth: 90
          _factor_name: 'neg_skew'
          _demean_method: 'average_factor_value_in_asset_class_for_instrument'
          _lookback_days: 365
  skewrv180:
     function: systems.provided.rules.factors.factor_trading_rule
     data:
          - 'rawdata.get_demeanded_factor_value'
     other_args:
          smooth: 45
          _factor_name: 'neg_skew'
          _demean_method: 'average_factor_value_in_asset_class_for_instrument'
          _lookback_days: 180
  accel16:
    function: systems.provided.rules.accel.accel
    data:
         - "rawdata.get_daily_prices"
         - "rawdata.daily_returns_volatility"
    other_args:
         Lfast: 16
  accel32:
    function: systems.provided.rules.accel.accel
    data:
         - "rawdata.get_daily_prices"
         - "rawdata.daily_returns_volatility"
    other_args:
         Lfast: 32
  accel64:
    function: systems.provided.rules.accel.accel
    data:
         - "rawdata.get_daily_prices"
         - "rawdata.daily_returns_volatility"
    other_args:
         Lfast: 64
#
forecast_cap: 20.0
#
forecast_scalars:
  accel16: 7.8170710605387095
  accel32: 5.563487137713779
  accel64: 3.896720541225276
  assettrend16: 3.549452858682833
  assettrend2: 10.846520114531351
  assettrend32: 2.3449234496490723
  assettrend4: 7.572334583056326
  assettrend64: 1.5465144366886119
  assettrend8: 5.190470936448635
  breakout10: 0.6031025130185256
  breakout160: 0.7388310187414805
  breakout20: 0.6742627921625178
  breakout320: 0.7366197028421859
  breakout40: 0.7036929411910525
  breakout80: 0.726260784624834
  carry10: 27.815707053556984
  carry125: 29.366474500729886
  carry30: 28.384062881349813
  carry60: 28.40072429176199
  momentum16: 4.104172020369661
  momentum32: 2.786994330124792
  momentum4: 8.539940954709955
  momentum64: 1.9093945630747895
  momentum8: 5.949404365193165
  mrinasset1000: 653.253194
  normmom16: 4.116536590599602
  normmom2: 12.388305650778637
  normmom32: 2.758872936017786
  normmom4: 8.614429965006694
  normmom64: 1.8706800701120874
  normmom8: 5.979138542342214
  relcarry: 49.44179741391023
  relmomentum10: 61.24026078373817
  relmomentum20: 86.50746400987076
  relmomentum40: 117.77937298659975
  relmomentum80: 159.87802982511536
  skewabs180: 4.590246757939031
  skewabs365: 2.351483885205172
  skewrv180: 5.244752769697409
  skewrv365: 3.002222097593425
#
# forecast combination
#
# Capital correction
#
percentage_vol_target: 30.0
notional_trading_capital: 14000
base_currency: "USD"
#
# Portfolio creation
#
instrument_div_multiplier: 1.4
risk_overlay:
  max_risk_fraction_normal_risk: 1.75
  max_risk_fraction_stdev_risk: 4.0
  max_risk_limit_sum_abs_risk: 4.0
  max_risk_leverage: 20.0
instrument_weights:
  KR3: 0.33
  V2X: 0.33
  EUR_micro: 0.33
forecast_weights:
  KR3:
    accel16: 0.0
    accel32: 0.0
    accel64: 0.038
    assettrend16: 0.025
    assettrend2: 0.0
    assettrend32: 0.025
    assettrend4: 0.0
    assettrend64: 0.025
    assettrend8: 0.025
    breakout10: 0.0
    breakout160: 0.063
    breakout20: 0.0
    breakout320: 0.063
    breakout40: 0.0
    breakout80: 0.051
    carry10: 0.032
    carry125: 0.038
    carry30: 0.032
    carry60: 0.038
    momentum16: 0.025
    momentum32: 0.038
    momentum4: 0.0
    momentum64: 0.038
    momentum8: 0.0
    mrinasset1000: 0.063
    normmom16: 0.025
    normmom2: 0.0
    normmom32: 0.025
    normmom4: 0.0
    normmom64: 0.025
    normmom8: 0.025
    relcarry: 0.063
    relmomentum10: 0.0
    relmomentum20: 0.0
    relmomentum40: 0.038
    relmomentum80: 0.051
    skewabs180: 0.032
    skewabs365: 0.032
    skewrv180: 0.032
    skewrv365: 0.032
  V2X:
    accel16: 0.0
    accel32: 0.0
    accel64: 0.0
    assettrend16: 0.034
    assettrend2: 0.0
    assettrend32: 0.034
    assettrend4: 0.0
    assettrend64: 0.034
    assettrend8: 0.0
    breakout10: 0.0
    breakout160: 0.085
    breakout20: 0.0
    breakout320: 0.085
    breakout40: 0.0
    breakout80: 0.0
    carry10: 0.042
    carry125: 0.051
    carry30: 0.042
    carry60: 0.051
    momentum16: 0.0
    momentum32: 0.051
    momentum4: 0.0
    momentum64: 0.051
    momentum8: 0.0
    mrinasset1000: 0.085
    normmom16: 0.034
    normmom2: 0.0
    normmom32: 0.034
    normmom4: 0.0
    normmom64: 0.034
    normmom8: 0.0
    relcarry: 0.085
    relmomentum10: 0.0
    relmomentum20: 0.0
    relmomentum40: 0.0
    relmomentum80: 0.0
    skewabs180: 0.042
    skewabs365: 0.042
    skewrv180: 0.042
    skewrv365: 0.042
  EUR_micro:
    accel16: 0.032
    accel32: 0.032
    accel64: 0.032
    assettrend16: 0.021
    assettrend2: 0.0
    assettrend32: 0.021
    assettrend4: 0.011
    assettrend64: 0.021
    assettrend8: 0.021
    breakout10: 0.0
    breakout160: 0.053
    breakout20: 0.0
    breakout320: 0.053
    breakout40: 0.042
    breakout80: 0.042
    carry10: 0.026
    carry125: 0.032
    carry30: 0.026
    carry60: 0.032
    momentum16: 0.021
    momentum32: 0.032
    momentum4: 0.0
    momentum64: 0.032
    momentum8: 0.016
    mrinasset1000: 0.053
    normmom16: 0.021
    normmom2: 0.0
    normmom32: 0.021
    normmom4: 0.011
    normmom64: 0.021
    normmom8: 0.021
    relcarry: 0.053
    relmomentum10: 0.0
    relmomentum20: 0.021
    relmomentum40: 0.032
    relmomentum80: 0.042
    skewabs180: 0.026
    skewabs365: 0.026
    skewrv180: 0.026
    skewrv365: 0.026
forecast_div_multiplier:
  KR3: 1.8846647325247878
  V2X: 1.6226404672702985
  EUR_micro: 1.858974667756371

#forecast_mapping:
#  EUR_micro:
#    a_param: 1.5588158032507866
#    b_param: 6.1045241189408745
#    threshold: 14.892916227772268
#  KR3:
#    a_param: 1.5660781779959168
#    b_param: 6.3334722999729625
#    threshold: 15.0545984767231